### ISSUE TITLE
Hello, how can I calculate path length with this code? Thank you

### ISSUE THREAD

**Issue by alperhanbay** [arimb/PurePursuit#1]

**Comment by arimb** [comment]
If you run [PathGenerator.py](https://github.com/arimb/PurePursuit/blob/master/PathGenerator.py) it outputs a csv with three columns: x, y, and velocity for each waypoint of the path. The path is comprised of a set of straight lines, so if you want to find the total length of the path you can sum the distances between each waypoint.

**Comment by Colneb** [comment]
Hey. Me and some of my peers have a few questions about your Pure Pursuit Algorithm. Could we maybe talk over Zoom, Microsoft Teams, Skype, etc about this code? Even a phone call would work.

**Comment by arimb** [comment]
My email address is in my profile. Send me an email with your questions and I can try to answer them (though it's been a few years since I've looked at this code so I don't know how well I remember it). If you haven't already, I also highly recommend going over [1712's whitepaper](https://www.chiefdelphi.com/t/paper-implementation-of-the-adaptive-pure-pursuit-controller/166552) upon which the majority of my code is based.
